global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'auth-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth-service:3001']

  - job_name: 'orders-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['orders-service:3002']

  - job_name: 'notifications-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['notifications-service:3003']
